### ISSUE TITLE
Return code 404 instead of 409 when file can not be found

### ISSUE THREAD

**Issue by Azzurite** [touhidurrr/UncivServer.xyz#1]
Currently, [Unciv checks for a `404` return code for custom server implementations](https://github.com/yairm210/Unciv/blob/16874f5da6f84b0e46d741ff89e3afc878f6a986/core/src/com/unciv/logic/multiplayer/storage/UncivServerFileStorage.kt#L25).

But UncivServer.xyz returns `409` when a file can't be found. This prevents Unciv from [showing a user-friendly message](https://github.com/yairm210/Unciv/blob/16874f5da6f84b0e46d741ff89e3afc878f6a986/core/src/com/unciv/ui/multiplayer/MultiplayerScreen.kt#L241). It also prevents the Android turn check background worker to function correctly, because [it also checks for if a file could not be found](https://github.com/yairm210/Unciv/blob/16874f5da6f84b0e46d741ff89e3afc878f6a986/android/src/com/unciv/app/MultiplayerTurnCheckWorker.kt#L321-L326), and if so, just stops checking them. But if it receives a `409`, it thinks that an actual problem has occured and stops everything.

It would be good if UncivServer.xyz could return [the HTTP status code `404`](https://en.wikipedia.org/wiki/HTTP_404) when a file is not found.

**Comment by touhidurrr** [comment]
Should be fixed with #2, response now:
```bash
~$ curl -i https://uncivserver.xyz/files/unknown_file
HTTP/2 404 
date: Wed, 25 May 2022 15:21:40 GMT
content-type: text/plain; charset=utf-8
content-length: 9
etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=kvK9wslEXQjRc%2FSH6phQun5OELEPRXLZt%2BxU17v5MPRxguqRXahHFAJ9aZ7RsNT1u5SIeL%2FD0Xn41%2Fj6HSpwU3WKCzZaaXlH3sOvhBjZPLso004s1On4omr2RSPciT7DwCc%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 710f43128ac049ae-SIN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

Not Found
```
