### ISSUE TITLE
/isalive endpoint should return valid JSON

### ISSUE THREAD

**Issue by CrsiX** [touhidurrr/UncivServer.xyz#19]
The reference server of Unciv, [UncivServer](https://github.com/yairm210/Unciv/blob/master/server/src/com/unciv/app/server/UncivServer.kt), is running at my localhost:8888 in this example.

```
$ curl "https://uncivserver.xyz/isalive"
true
$ curl "http://localhost:8888/isalive"
{authVersion: 0}
```

I would highly recommend to return some valid JSON at the `/isalive` endpoint of your unciv server implementation, even if it's telling you no supported features, like `{authVersion: 0}` as shown above. At the moment, the client just gives up on parsing the response and uses an empty `ServerFeatureSet` object, which is fundamentally the same behavior. But I think it would be much cleaner for other client implementations if the response could be parsed.

This would allow a client to "detect broken server implementations" and e.g. show some warning. At the moment, it's just ignored.

**Comment by CrsiX** [comment]
I just saw that [this](https://github.com/oynqr/rust_unciv_server) and [this](https://github.com/Mape6/Unciv_server) and [this](https://gitlab.com/azzurite/unciv-server) server implementations return plain `true` as well. Now I wonder: do you know who introduced this API definition? Because if all of the existing implementations use `true` at that endpoint, then the client should be fine with it (even though I don't really understand yet).

I guess I would therefore close the issue after clarification.

**Comment by touhidurrr** [comment]
try `replit.uncivserver.xyz` to test the beta UncivServer.xyz
haven’t worked on UncivServer recently so o forgot which version the repo is at.
but i remember moving beta code to replit cause it was not working as intended.

**Comment by CrsiX** [comment]
`replit` serves `{"authVersion":1}`, so I conclude it also provides authentication.

Nevertheless, do you think `{"authVersion":0}` would be good as return value for the normal `uncivserver.xyz`?

**Comment by CrsiX** [comment]
If you do so, could you please specify the `Content-Type` of your return to be `application/json`? It's `text/plain` at the moment.

**Comment by touhidurrr** [comment]
> Nevertheless, do you think {"authVersion":0} would be good as return value for the normal uncivserver.xyz?

Not sure what you mean by **_normal_** **UncivServer.xyz**. Also, why not just keep it `true`?

> If you do so, could you please specify the Content-Type of your return to be application/json? It's text/plain at the moment.

Done for replit server.

**Comment by CrsiX** [comment]
> Not sure what you mean by normal UncivServer.xyz. Also, why not just keep it true?

With "normal" I meant the one hosted at https://uncivserver.xyz.
But don't worry, I will just continue with parsing the `true` value, especially since the other three implementations do it the same way.

> Done for replit server. 

Thanks.
